# Generated by Django 5.2 on 2025-04-14 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('next_prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='game.prompt')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='responses', to='game.prompt')),
            ],
        ),
    ]
