# Generated by Django 5.2 on 2025-04-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='sword',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
