# Generated by Django 5.2 on 2025-04-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_response_sword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='sword',
            field=models.BooleanField(default=False),
        ),
    ]
