# Generated by Django 5.2 on 2025-04-17 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_response_sword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='sword',
        ),
    ]
